# Generated by Django 2.1.3 on 2019-06-15 20:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название понятия')),
                ('depth', models.IntegerField(default=0, editable=False, verbose_name='Глубина расположения вершины')),
                ('lvl', models.IntegerField(default=3, verbose_name='Нормативный уровень освоения')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_alpha', models.FloatField(default=2, max_length=4, verbose_name='время на восприятие одного понятия')),
                ('k_knowledge', models.FloatField(default=2, max_length=4, verbose_name='коэффициент усложнения при создании связей')),
                ('k_practise', models.FloatField(default=4, max_length=4, verbose_name='коэффициент усложнения при практическом освоении умения')),
                ('k_skill', models.FloatField(default=8, max_length=4, verbose_name='коэффициент усложнения при приобретении навыка')),
            ],
        ),
        migrations.AddField(
            model_name='edges',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_of', to='treegraph.Nodes', verbose_name='Вершина-потомок'),
        ),
        migrations.AddField(
            model_name='edges',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treegraph.Nodes', verbose_name='Вершина-родитель'),
        ),
    ]
