# Generated by Django 2.1.3 on 2018-12-16 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название понятия')),
                ('lvl', models.IntegerField(default=0, verbose_name='Этап изучаемого предмета')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_alpha', models.IntegerField(default=2, verbose_name='время на восприятие одного понятия')),
                ('k_knowledge', models.IntegerField(default=2, verbose_name='коэффициент усложнения при создании связей')),
                ('k_practise', models.IntegerField(default=4, verbose_name='коэффициент усложнения при практическом освоении умения')),
                ('k_skill', models.IntegerField(default=8, verbose_name='коэффициент усложнения при приобретении навыка')),
                ('time_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treegraph.Nodes')),
            ],
        ),
        migrations.AddField(
            model_name='edges',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_of', to='treegraph.Nodes', verbose_name='Вершина-потомок'),
        ),
        migrations.AddField(
            model_name='edges',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treegraph.Nodes', verbose_name='Вершина-родитель'),
        ),
    ]
