# Generated by Django 2.1.3 on 2018-12-27 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Levels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0, verbose_name='Уровень изучения вершины')),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название понятия')),
                ('lvl', models.IntegerField(default=0, verbose_name='Этап изучаемого предмета')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(max_length=20, verbose_name='Группа студента')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя студента')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия студента')),
            ],
        ),
        migrations.CreateModel(
            name='TimeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_alpha', models.CharField(default=2, max_length=4, verbose_name='время на восприятие одного понятия')),
                ('k_knowledge', models.CharField(default=2, max_length=4, verbose_name='коэффициент усложнения при создании связей')),
                ('k_practise', models.CharField(default=4, max_length=4, verbose_name='коэффициент усложнения при практическом освоении умения')),
                ('k_skill', models.CharField(default=8, max_length=4, verbose_name='коэффициент усложнения при приобретении навыка')),
            ],
        ),
        migrations.AddField(
            model_name='levels',
            name='node_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='treegraph.Nodes', verbose_name='связанная вершина'),
        ),
        migrations.AddField(
            model_name='levels',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treegraph.Students', verbose_name='Студент'),
        ),
        migrations.AddField(
            model_name='edges',
            name='child',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='child_of', to='treegraph.Nodes', verbose_name='Вершина-потомок'),
        ),
        migrations.AddField(
            model_name='edges',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treegraph.Nodes', verbose_name='Вершина-родитель'),
        ),
    ]
