# Generated by Django 2.1.3 on 2018-12-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treegraph', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timesettings',
            name='k_knowledge',
            field=models.FloatField(default=2, max_length=4, verbose_name='коэффициент усложнения при создании связей'),
        ),
        migrations.AlterField(
            model_name='timesettings',
            name='k_practise',
            field=models.FloatField(default=4, max_length=4, verbose_name='коэффициент усложнения при практическом освоении умения'),
        ),
        migrations.AlterField(
            model_name='timesettings',
            name='k_skill',
            field=models.FloatField(default=8, max_length=4, verbose_name='коэффициент усложнения при приобретении навыка'),
        ),
        migrations.AlterField(
            model_name='timesettings',
            name='t_alpha',
            field=models.FloatField(default=2, max_length=4, verbose_name='время на восприятие одного понятия'),
        ),
    ]
