# Generated by Django 2.1.3 on 2018-12-16 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treegraph', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timesettings',
            name='time_setting',
        ),
        migrations.AddField(
            model_name='nodes',
            name='time_setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='treegraph.TimeSettings'),
            preserve_default=False,
        ),
    ]
