# Generated by Django 2.1.3 on 2018-12-27 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treegraph', '0002_auto_20181227_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='node_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treegraph.Nodes', verbose_name='связанная вершина'),
        ),
    ]
