# Generated by Django 2.1.3 on 2018-12-16 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treegraph', '0002_auto_20181217_0531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodes',
            name='time_setting',
        ),
    ]
